version: "3"

services:
  tomcat:
    build: .
    ports:
      - "8081:8080"
    volumes:
    	#### Named space volumes
      - binaries:/usr/local/tomcat/webapps
        #### bind mounting
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml

volumes:
  binaries:
